### ISSUE TITLE
Update the taskcat version to 0.9.23 from current 0.9.19

### ISSUE THREAD

**Issue by arniesaha** [ShahradR/action-taskcat#82]
Hello @ShahradR,

Hope you're doing well! I've been trying to set this up, taskcat action with one of my CF repositories. And, thank you for the easy setup. However, there's a potential cfn-lint issue that I'm currently facing with the existing taskcat version this repo deploys. i.e. 0.9.19

There's a CFN resource in my template:
`NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties: 
      AmiType: AL2_x86_64
      CapacityType: !Ref NodeInstanceCapacity
      ClusterName: !Sub ${EKSControlPlane}`
      
Where version 0.9.19 fails 'CapacityType: !Ref NodeInstanceCapacity' as a Resource Not Found.

`version 0.9.19

[WARN   ] : A newer version of taskcat is available (0.9.23)
[INFO   ] : To upgrade pip version    [ pip install --upgrade taskcat]
[INFO   ] : To upgrade docker version [ docker pull taskcat/taskcat ]`

`[ERROR  ] :     line 200 [3002] [Resource properties are valid] Invalid Property Resources/NodeGroup/Properties/CapacityType`

Perhaps relates to https://github.com/aws/aws-cdk/issues/12154

And, I initially set up the taskcat workflow on local as well as on CodePipeline using 0.9.23 and my taskcat test do pass and deploy. 

Based on this:
https://github.com/aws-quickstart/quickstart-taskcat-ci

Is there a way we could update the taskcat version. Although the Dockerfile has the latest pull, not sure if it's updated though.

Any assistance is much appreciated

Thanks,
Arnab

**Comment by ShahradR** [comment]
Hi @arniesaha, thanks for reaching out!

I think you're right—it doesn't look like the container is running the latest version of taskcat. I just pushed a release out for you which introduces a new input parameter called `update_taskcat`. If you set that to `true` in your workflow file, the action will run `pip install --upgrade taskcat` before executing your tests, which should upgrade you to v0.9.23!

Try updating your GitHub Action workflow file like so, and see if this helps with your issue?

```diff
  - name: Run taskcat test run
-   uses: ShahradR/action-taskcat@v1
+   uses: ShahradR/action-taskcat@v1.2.0
    with:
      commands: test run
+     update_taskcat: true
```

Let me know what you think, and thanks again for the feedback—it's really appreciated! 😄

**Comment by arniesaha** [comment]
Hi @ShahradR 

Thanks for the prompt update. Yes, this does update the taskcat version to 0.9.23. Although, the lint issue I was facing still persists. Not sure as the same templates work on 0.9.23 and python v3.7 & 3.8 

But, as of now, I'm passing disable lint in the command to get the action to run successfully.

`test run -t dev --lint-disable`

Thanks though, will continue to use this action and figure out the lint issue.

**Comment by ShahradR** [comment]
Hi @arniesaha!

I was thinking, maybe we need to update `cfn-lint` too?

I pushed a new commit that adds another input parameter called `update-lint`. I still need to add some tests, so I haven't merged it into the main branch yet, but give this a try and see if it does the trick?

```diff
  - name: Run taskcat test run
-   uses: ShahradR/action-taskcat@v1.2.0
+   uses: ShahradR/action-taskcat@9a5e4e1eeef3fb2b0b3c79a2f9eeccc8ded352dd
    with:
      commands: test run
      update_taskcat: true
+     update_lint: true
```

**Comment by arniesaha** [comment]
Hi @ShahradR !

Yes, this did the trick :)

I will be testing further with my stack as well! But, it did pass through the lint and started creating the stack :) 

Thanks for the great work +1

**Comment by ShahradR** [comment]
That's awesome!!! 🥳 

I'll keep this ticket open until the code changes are merged into the main branch. If there is anything else I can help with though, feel free to comment here or open a new ticket!

I _might_ also change the input parameter's name from `update_lint` to `update_cfn_lint`, just to make it more descriptive. I'll let you know if I end up making that change!

**Comment by arniesaha** [comment]
Thanks! Appreciate it :)

Let me know once you merge it and if the commands are updated: would need to update my workflow appropriately.

**Comment by ShahradR** [comment]
Hi @arniesaha, sorry for the delay!

I just pushed release 1.3.0 of the action with the cfn_lint update flag! I did end up renaming the input parameter name to `update_cfn_lint` though.

Since your workflow is referencing the action using a commit SHA, your builds should continue working using `update_lint` until you start referencing the new release, so hopefully this shouldn't cause too much of a disruption with your pipelines!

Let me know if you run into any issues!

```diff
  - name: Run taskcat test run
-   uses: ShahradR/action-taskcat@9a5e4e1eeef3fb2b0b3c79a2f9eeccc8ded352dd
+   uses: ShahradR/action-taskcat@v1.3.0
    with:
      commands: test run
      update_taskcat: true
-     update_lint: true
+     update_cfn_lint: true
```

**Comment by arniesaha** [comment]
Thanks @ShahradR 

I have updated the workflow to use 1.3.0, testing it atm. 👍

**Comment by arniesaha** [comment]
Hi @ShahradR 

Something has broken with the workflow yesterday.

`ERROR: unsatisfiable constraints:
    nodejs-12.21.0-r0:
      breaks: world[nodejs=12.20.1-r0]
      satisfies: npm-12.21.0-r0[nodejs]
    npm-12.21.0-r0:
      breaks: world[npm=12.20.1-r0]
  The command '/bin/sh -c apk add --no-cache nodejs=12.20.1-r0 npm=12.20.1-r0 && rm -rf /var/cache/apk/*' returned a non-zero code: 2
  Warning: Docker build failed with exit code 2, back off 9.528 seconds before retry.`
  
  
![image](https://user-images.githubusercontent.com/3646287/109051122-33eff000-7700-11eb-85d9-de4e5dbd8e80.png)

  
Let me know if we can fix this? My workflows just stopped working :|


Thanks for the help again!

Regards,
Arnab

**Comment by ShahradR** [comment]
Hi @arniesaha, thank you for flagging this!

It looks like the Node.js and npm packages in the Alpine repositories have been updated, and the versions referenced in the Dockerfile are no longer available.

I'm tracking this issue in ShahradR/action-taskcat#74 with the hopes of finding some long-term solution, but in the meantime, I just pushed a new release which bumps the Node.js and npm versions. Give it a try, and see if that gets your workflows running again?

**Comment by arniesaha** [comment]
Thanks, @ShahradR for the prompt update.

Have been using the updated version 1.3.1 and is currently working as expected +1

**Comment by ShahradR** [comment]
That's awesome!!! 🥳 

I'll go ahead and close this issue, but is anything comes up again, feel free to either re-open this issue or create a new one!

And thank you so much for this ticket—I'm really glad we were able to add these update flags to the action!
